name: Local Governance Action Test

on:
  workflow_dispatch:

jobs:
  test-governance-action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t governance-action .

      - name: Run Governance check
        run: |
          docker run --rm \
            -e INPUT_GOVERNANCE_SERVICE=http://host.docker.internal:8989/api \
            -e INPUT_GOVERNANCE_AUTH=test-token \
            -e INPUT_RULE_ID=test-rule \
            -e INPUT_API_PATH=/data/openapi.yaml \
            -v $(pwd)/test-data/openapi.yaml:/data/openapi.yaml \
            governance-action 